# Generated by Django 5.2.5 on 2025-08-25 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('moderation', 'На модерации'), ('rejected', 'Отклонено')], default='moderation', max_length=20, verbose_name='Статус публикации'),
        ),
    ]
